## Service Name-Group Mapping
ceilometer_services:
  ceilometer-collector:
    group:
      - ceilometer_collector
    service_name: ceilometer-collector
  ceilometer-agent-notification:
    group:
      - ceilometer_agent_notification
    service_name: ceilometer-agent-notification
  ceilometer-polling:
    group:
      - ceilometer_agent_central
      - ceilometer_agent_compute
    service_name: ceilometer-polling

usage_meters_metadata_keys:
  - UAI

usage_meters_pip_package: "git+https://github.com/absalon-james/usage_meters.git#egg=usage_meters"
